version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/teldrive
    restart: always
    container_name: teldrive
    volumes:
      - ./teldrive.db:/teldrive.db:rw
      - ./config.toml:/config.toml
    ports:
      - 8080:8080
