name: Goreleaser-Dev

on:
  push:
    tags:
      - "[0-9].[0-9]+.[0-9]+-dev"

permissions: write-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.dev.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}